### ISSUE TITLE
100% latency increase on routing/v1 API

### ISSUE THREAD

**Issue by guseggert** [ipni/storetheindex#1128]
Something I noticed this morning from Hydra metrics: at around 2022-12-16T10:36:00Z, the cid.contact/routing/v1 endpoint experienced a sudden 100% increase in latency, p50 went from ~30ms to ~60ms. This doesn't correlate with any increase in request rate to Hydras or other client-side metrics, so it seems likely to be a server-side issue. Perhaps there was a deployment around that time?

Graph:
![Screenshot_20221216_090300](https://user-images.githubusercontent.com/877588/208114923-0e90be3f-eb41-492d-95b8-9cf80e4dee1f.png)

([source](https://protocollabs.grafana.net/d/lNGQTv9Zz/hydra-boosters?orgId=1&from=1671180797549&to=1671194393978&var-flight=test-.*&viewPanel=116))

**Comment by masih** [comment]
Assuming this is `prod` and times are in UTC?

**Comment by guseggert** [comment]
The UTC time is in the message (2022-12-16T10:36:00Z), the image is in my local tz (UTC-5).

**Comment by masih** [comment]
Thanks Gus; looking

**Comment by guseggert** [comment]
Fixed graph to use UTC tz

**Comment by masih** [comment]
Origin latency at CloudFront, and upstream latency at nginx ingress controller both look flat. There has not been any deployments today. 

This leaves me to believe there is either something we are not measuring at cid.contact or the root cause is outside of cid.contact.  I am trying to think if there is an alternative source via which we could confirm the latency increase; do gateways observe the same latency increase for example (even though they are not using the new HTTP delegated routing endpoint)? Under the hood the requests are translated and hit the same execution path down the line. 

<img width="627" alt="image" src="https://user-images.githubusercontent.com/301855/208117494-44ad0eb9-e82b-4754-b829-a8a448141cc4.png">

<img width="755" alt="image" src="https://user-images.githubusercontent.com/301855/208117548-1c5195df-3241-404d-9a1c-f691f78d6b49.png">

**Comment by guseggert** [comment]
It's certainly possible that this is caused by something internal to the Hydras, causing them to write the req and read the response more slowly, but those are usually gradual degradations or align with some other metric like request rate.

Also I do not see this same spike from prod Hydras which are still running reframe.

**Comment by gammazero** [comment]
Cannot reproduce (no more hydras), and no follow-up on this specific issue.
