### ISSUE TITLE
Support extended providers in reader privacy

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#1190]
Currently extended providers metadata is [persisted in registry](https://github.com/ipni/storetheindex/blob/main/internal/ingest/linksystem.go#L254) only. The stored information is then [appended](https://github.com/ipni/storetheindex/blob/main/server/finder/handler/finder_handler.go#L79-L117) to the records returned by core `indexer.Engine` in find handler.

The current integration with `dhstore` encrypts and writes values [directly from `indexer.Engine`](https://github.com/ipni/go-indexer-core/blob/main/engine/engine.go#L56-L60). This means the metadata specified by extended providers is never seen by the engine and therefore will not be available in reader privacy queries.

* Understand implications of extended provider on reader-proivacy path.
  *  For example, when the metadata changes, encrypted records need to be removed.
* Integrate storetheindex registry with `dhstore` such that the extended provider records are also available in  reader-privacy enabled queries.

**Comment by ischasny** [comment]
In `storetheindex` all provider-related data (including `ExtendedProviders`) is served form the `registry` while the index itself - from the `valueStore`. If to hit https://ago.dev.cid.contact/providers/https://ago.dev.cid.contact/providers/12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC in the browser - one can see that `ExtendedProvider`s  are a part of `ProviderInfo` and are served in open, even though `ago` is a "double hashed" instance. 

In privacy preserving lookups in order to construct the full result, the client has to do three roundtrips:
1. Get `enc(valueKey, multihash)` by `hash(multihash)`
2. Get `enc(metadata, valueKey)` by `hash(valueKey)`
3. Get [ProviderInfo](https://github.com/ipni/storetheindex/blob/main/internal/registry/registry.go#L77) by `peer.ID`. `peer.ID` is decoded from `valueKey`. @gammazero is working on integrating `registry` into `dhstore` so this communication is going to be privacy preserving too. 

The step 3 can be partially avoided - clients can cache `ProviderInfo`s locally with some reasonable expiry time. As `ProviderInfo` contains `ExtendedProvider`s in it the latter becomes also cacheable  out of the box (client side caching isn't in scope for this task). Currently `ExtendedProvider`s get "unwrapped" inside [finder_handler](https://github.com/ipni/storetheindex/blob/main/server/finder/handler/finder_handler.go#L79) on the server. That can't be done for privacy preserving lookups as the server doesn't have decryption keys and hence doesn't know how to "merge" the results. Hence the "unwrapping" logic will have to move down to the [DHClient](https://github.com/ipni/storetheindex/blob/main/api/v0/finder/client/http/dhash_client.go#L31), which is the only place where the data is accessible in open and merging rules can be applied. 

The `ProviderInfo` structure has four moving parts in it - `AddrInfos`, `metadata`, chain-level `ExtendedProviders` and context-level `ExtendedProviders`. Each of the parts can be updated independently at different points in time. It will be reasonable to store each of these parts separately from each other as "partial update" over an encrypted payload is not possible. `AddrInfos` and chain-level `ExtendendedProviders` are maintained at the `peerID` level, while `metadata` and contextual `ExtendedProviders` - at the `contextID` level. Hence the first two can be encrypted and looked up by `peerID`, while the last two by `valueKey`. We do already have an endpoint that returns `enc(metadata, valueKey)` by `hash(valueKey)`. So I propose the following changes here:
1. Extend `GetMetadataResponse` so that it returns the following structure:
```
GetMetadataResponse struct {
      EncryptedMetadata EncryptedMetadata `json:"EncryptedMetadata"`
      EncryptedExtendedProviders EncryptedExtendedProviders `json:"EncryptedExtendedProviders,omitempty"` // an optional field for contextual extended providers
}
```
with both fields encrypted with `valueKey`
2. Add a new endpoint `/providerinfo/hash(peerID)` (CC @gammazero's work) that would return something like that:
```
GetProviderInfoResponse struct {
      EncryptedAddrInfo EncryptedAddrInfo `json:"EncryptedAddrInfo"`
      EncryptedExtendedProviders EncryptedExtendedProviders `json:"EncryptedExtendedProviders,omitempty"` // an optional field for chain-level extended providers
}
```
with both fields encrypted with `peerID`
3. Update `storetheindex` and `dhstore` to store:
- `enc(ContextualExtendedProviders, valueKey)` by `hash(valueKey)`
- `enc(AddrInfo, peerID)` by `hash(peerID)`
- `enc(ChainLevelExtendedProviders, peerID)` by `hash(peerID)`

That way any update to metadata / addrInfos / chain level EPs / contextual EPs would overwrite the previous values so we won't need to care about partial updates and removals.  

I propose doing that in two iterations:
1. Move down [unwrapping](https://github.com/ipni/storetheindex/blob/main/server/finder/handler/finder_handler.go#L79) logic to the `DHClient`. Under the hood, the client would use the existing [providers](https://ago.dev.cid.contact/providers/12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC) endpoint for fetching `ProviderInfo` including `ExtendedProviders` and merging the final result locally. 
2. Once `registry` has been integrated into `dhstore` - update `DHClient` to query an encrypted version of `ProviderInfo` using the new endpoint as well as to use contextual `ExtendedProviders` from the metadata response. 

LMK what you think @masih @gammazero

**Comment by masih** [comment]
> all provider-related data (including ExtendedProviders) is served form the registry

Not quite true considering indexer core persists `Metadata`. Results from registry [are appended](https://github.com/ipni/storetheindex/blob/main/server/finder/handler/finder_handler.go#L72) to the ad level metadata; no?

>  even though ago is a "double hashed" instance.
> query an encrypted version of `ProviderInfo`

We came to the conclusion to [not encrypt provider info](https://www.notion.so/pl-strflt/Switzerland-Colo-a125250185384d778f2304c0c2c5c75d#6fa41170a6864782b71345ad92e60d58) at all in the first iteration of reader privacy. right?


This issue is more about the incomplete list of value keys being sent back to the client in step 1, than the step 3. For example, what would be the list of encrypted value keys that we return for [this](https://ber.dev.cid.contact/cid/bafybeiegmu3r7wozpwalilsoxroti6kzvbuxezram25arkxjt7lbe2mcqi) query? Note that the bitswap protocol support for that CID is from a chain-level extended provider advertisement.

**Comment by ischasny** [comment]
> Not quite true considering indexer core persists Metadata. Results from registry [are appended](https://github.com/ipni/storetheindex/blob/main/server/finder/handler/finder_handler.go#L72) to the ad level metadata; no?

By provider-related I mean info that is maintained at the peer id level, not at the deal / context id level. So yes, metadata gets persisted in dhstore but the final result is a merge of provider-level data + deal level data. 

> For example, what would be the list of encrypted value keys that we return for [this](https://ber.dev.cid.contact/cid/bafybeiegmu3r7wozpwalilsoxroti6kzvbuxezram25arkxjt7lbe2mcqi) query?

Let me try to go step by step with the proposed workflow:
1. The client would query value keys for `hash(12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC)` and get back one value key of `enc(12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC + AXESILXu0EY83fnKPNPFmKT8x7af4t/EFfHRu15OHPhsytVJ)`
2. The client would query metadata for `hash(12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC + AXESILXu0EY83fnKPNPFmKT8x7af4t/EFfHRu15OHPhsytVJ)` and get back 
```
GetMetadataResponse struct {
      EncryptedMetadata: enc(kBKjaFBpZWNlQ0lE2CpYKAABgeIDkiAg1S14LwfUApTaDwEEgFUJK5iLX9/1oKY06lKWNjlQcCZsVmVyaWZpZWREZWFs9W1GYXN0UmV0cmlldmFs9A==),
      EncryptedExtendedProviders: nil
}
```
3. The client would extract peer id from the value key and query provider info for  `12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC` (eventually that will be hashed too) and get back
```
GetProviderInfoResponse{
    AddrInfo: {
         "ID": "12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC",
         "Addrs": [
           "/ip4/209.94.92.6/tcp/24001"
         ]
   },
   ExtendedProviders: {
         [{
              "ID": "12D3KooWHf7cahZvAVB36SGaVXc7fiVDoJdRJq42zDRcN2s2512h",
              "Addrs": [
                   "/ip4/209.94.92.6/udp/24123"
               ],
               Metadata: "gBI="
              },
         }
       ]
}
```

Eventually step 3 will be encrypted too. By merging results from 2 and 3 the client would get the  payload in question.

**Comment by masih** [comment]
I think your proposal is to not return value-keys associated to extended providers at all in step 1 of workflow above and instead get them from `/providers` endpoint? 

If so how would that work for systems like IPFS that:
* have no notion of metadata, and
* use `/providers` to fetch addrs only via `routing.PeerRouting` interface implementation.

**Comment by ischasny** [comment]
Ok, great question. 

Right now IPFS relies on a translation layer that can take stuff from a delegated routing protocol (or crawl a DHT) and transform it to IPNI advertisements. So it's a responsibility of that layer to fill in correct metadata that IPFS implicitly assumes. 

So what if one wants to use Extended Providers with IPFS.  IPFS expects a to step process:
1. Give a multihash and get back a list of peer ids *that support bitswap*
2. Give a peer id and get a bunch of multiaddresses *that bitswap is supported on*

So, on the step 1 the IPNI client will do the full job - it will get value keys, get metadata, get provider info and extended providers, merge it all together and then return a filtered list of peer ids that support bitswap only. Then on the step 2, IPFS will be able to use `PeerRouting` implementation to do the rest.

**Comment by masih** [comment]
> So, on the step 1 the IPNI client will do the full job - it will get value keys, get metadata, get provider info and extended providers, merge it all together and then return a filtered list of peer ids that support bitswap only.

I'm i feel like I am missing something :) How does merging it all together work at the presence of double hashing?

**Comment by ischasny** [comment]
Remember that merging happens **on the client side** that is aware of the original multihash. The client can decrypt the value keys, decrypt metadata, fetch provider info and extended providers either remotely or from a cache, merge it all locally (in the same way as we do in finder_handler), filter out not bitswap protocols if needed and return a list of peer IDs to the callee.

**Comment by ischasny** [comment]
We need to have a code that can filter out providers that do support bitswap from the ones that don't. That can be done either on the client or on the server. The latter would assume revealing multihashes to the server that we don't want to do.  In the former case - one will have to do an IPNI specific query (i.e. fetch and decrypt metadata). Hence there should be an abstraction in the IPFS routing system that have different "fetch peer IDs" imementations for different routing systems.

**Comment by gammazero** [comment]
I dont really understand the purpose for looking up provider information using a hash(peer.ID).  It is trivial to walk the public block chain and get all the provider IDs, and compute their hash. Now I have a mapping of hash(peer.ID)->peer.ID and for any hash(peer.ID) that is seen, the peer.ID is immediately available. So, hashing the peer.ID protects nothing, but introduces additional complexity.

Looking up provider info using `hash(peer.ID)` does not prevent the indexer, or anyone else, from knowing the `peer.ID` of the provider. This means that:

> Add a new endpoint `/providerinfo/hash(peerID)`

Is unnecessary. Once `peer.ID` is decoded from `valueKey`, I do not see any point in hashing the `peer.ID` to look up the information for that provider.

Do we need to change anything regarding STI's ability to list providers and import them from other indexers? It does not seem to make sense to remove that, even if the indexer is referring to provider info using only hash(peer.ID), because listing providers can be easily recreated as follows:
- Read provider IDs from public block chain.
- For each providerID, query indexer with `/providerinfo/hash(provider)`
- Collect all non-404 responses into a list
- Display list using original providerID from block chain.

The indexer itself could do that as a matter of convenience and humor.

What about the publisher ID and addresses which also are part of the ProviderInfo? Since 90% of the time both the ID and the addresses are the same as the provider ID and addresses, do we need to protect those also? Doing that would introduce much more complexity including changing how announcements work. No doing it will make protecting the provider ID and addresses meaningless.

The `/providers` could change to `/publishers`, but since their is a 1:1 mapping between publishers and providers, it is really the same information.

**Comment by ischasny** [comment]
Agree that looking up a `ProviderInfo` by `peerId` might be unnecessary. IPFS's double hashing spec says that they want to encrypt `ProviderInfo` so I added that to be compatible.

I guess the punchline here is that I propose to query `ExtendedProviders` by `hash(peerId)` so that they can be added into the final result on the client side.

**Comment by gammazero** [comment]
> I propose to query ExtendedProviders by hash(peerId)

Given the above about there being no point in querying provider info using a hashed peer.ID, this seems the same. There is no point is using hash(peer.ID) for anything. I can requesting context level extended provider info  using hash(peer.ID + contextID), but there is a context ID there.

**Comment by ischasny** [comment]
Am I right in understanding that you propose querying *chain-level* Extended Providers by `peerID`, unencrypted, but querying contextual Extended Providers by `hash(ValueKey)` alongside the metadata?

**Comment by gammazero** [comment]
The first part, yes.  The 2nd part, I think so, but I need to think through that a bit more.

**Comment by ischasny** [comment]
We can theoretically leave contextual providers in the Provider Info struct, in open, as they are now. That'd be more consistent probably rather than encrypting the former but not encrypting the latter.

**Comment by ischasny** [comment]
Fixed by https://github.com/ipni/storetheindex/pull/1228
