### ISSUE TITLE
Add configuration parameters for ttl and maxSize into dhash_client cache

### ISSUE THREAD

**Issue by ischasny** [ipni/storetheindex#1231]
`dhash_client` caches `ProviderInfo`s to optimise privacy preserving requests roundtrip times. Think about adding 2 new configuration options:
* `CacheTTL`, which is currently hardcoded to 5 minutes. The value of 5 minutes is chosen as large enough to smooth request bursts -  when someone fetches the same `ProviderInfo` over and over again within a short period of time (for example in a loop). 5 minutes is also small enough so that caches get periodically refreshed and updates get propagated down to the clients within a reasonable timeframe. Setting ttl to a large value might result into outdated information returned to privacy preserving lookups that will harm user experience. 
* `CacheMaxSize`. Currently the number of providers is small enough to not to be a concern. cid.contact has around 400 providers which won't require much RAM if kept in memory. As IPNI ecosystem grows, specifically when smaller IPFS nodes start providing their indexes, the number of providers might grow significantly. When a cache grows up to the configured max size - the oldest records should be evicted.

**Comment by gammazero** [comment]
Confiugrable cache TTL has been implemented, [here](https://github.com/ipni/go-libipni/blob/main/pcache/option.go#L106-L114).

Cache max size will not currently be implemented. Likely all provider information will be cached, for now, due to the expense of retrieving it from multiple sources. If it becomes too big for memory, then it can be backed by local storage.

@ischasny I am going to close this issue because I think that `go-libipni/pcache` addresses these. Please reopen if this is not the case.
