### ISSUE TITLE
find latency metric should split 'findbatch' and 'find'

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#179]
they will take different amounts of time potentially

**Comment by gammazero** [comment]
@willscott Is this still useful to have a different metric when looking for 1 or for more than 1 multihash?

**Comment by willscott** [comment]
in practice we're only using `find`. if @arnabguin is using findbatch, it might be useful for their usecase to have it split out?

**Comment by gammazero** [comment]
Find is implemented using a batch size of 1. The reason there were two separate APIs is so that find can be very simple allowing a person to construct only a URL to execute a find. Splitting the metric between find and findBatch is only separating the letency measurement of batch sizes of one from all other batch sizes.

A larger batch size will always have a lower average latency per multihash because there are fewer queries to the core valuestore. A more useful measurement would be average multihash latency as a function of batch size.

**Comment by masih** [comment]
> A more useful measurement would be average multihash latency as a function of batch size.

This makes sense 👍

**Comment by TorfinnOlsen** [comment]
Closing all issues > 6 months without attention.
