### ISSUE TITLE
extend mirroring to work for multiple providers

### ISSUE THREAD

**Issue by willscott** [ipni/storetheindex#674]
currently the mirror only works for 1 provider

**Comment by gammazero** [comment]
Mirroring for indexers is implemented as a storage facility for all advertisements from all providers. The ads and multihash entries are stored in CAR files.

The provider mirroring is a separate thing, and indexers do not currently use this to serve advertisements as an alternative advertisement publishing location. Indexers would more likely share their mirror with other specific indexers as an S3 CAR mirror and not as an index provider.

@willscott  If we want indexers to share their mirror as an index provider, then we can keep this issue. Otherwise, if there is not intention of doing that, lets close it.
