### ISSUE TITLE
Uncached find requests time out

### ISSUE THREAD

**Issue by honghaoq** [ipni/storetheindex#863]
Find requests from Hydra for which no cached entry is present, time out. Note the timeout set by Hydra client is 1 second. 
Understand how to reduce origin latency in indexstar.

**Comment by masih** [comment]
Relates to https://github.com/filecoin-shipyard/indexstar/issues/12 

indexer nodes that are unavailable should be excluded from the backend. Otherwise every request hitting indexstar will pay a n internal timeout cost which reslts in higher origin latency as observed in ColudFront caching layer and ultimately a timeout on hydra side.

**Comment by masih** [comment]
Changes in #864 significantly reduced the timeouts and origin response latency visible on both indexer and hydra metrics:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/301855/193024040-daa0f622-3906-4536-8963-e3e14c002e12.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/301855/193024074-631d7e83-0ab4-43c9-8d3a-da9262ecd7cc.png">
<img width="616" alt="image" src="https://user-images.githubusercontent.com/301855/193024101-9dc9aa0e-62e1-4fd9-ab61-46aac3df498d.png">


Question @honghaoq: What is the target QoS we are aiming for here? Is the reduction above good enough? if not please quantify.

**Comment by gammazero** [comment]
This has been fixed by internal routing improvements. Including high-performance provider information cache in indexstar and in dhfind/dhstore, and much more.
