### ISSUE TITLE
Perform a controlled experiment that compares ingest and lookup performance between pebble and sth

### ISSUE THREAD

**Issue by masih** [ipni/storetheindex#910]
Run two fresh nodes from a local ad chain source between a pebble backed and sth backend and measure:
* storage size
* time to full ingest
* lookup latency

**Comment by gammazero** [comment]
I did a controlled test of two new (empty store) indexers reading only from NFT provider, syncing a depth of 1000 ads from the same head.  One indexer was running pebble, one running STH, otherwise configuration was identical. Both finished ingesting the ads at almost the same time, and both finished at the same ad, having the same number of multihashes ingested.

After completing ingestion, here are the storage sizes:
STH:
```
3.3M    /data/datastore
342M    /data/valuestore-sth
```
Pebble:
```
3.3M    /data/datastore
529M    /data/valuestore-pebble
```
After 30 minutes, these sizes have not changed.

However, after restarting the indexers, Pebble storage is much smaller:
STH:
```
96K     /data/datastore
372M    /data/valuestore-sth
```
Pebble:
```
96K     /data/datastore
103M    /data/valuestore-pebble
```

Querying a random sampling of the multihashes from the indexed data indicates that both indexers successfully return all indexes.

So, as part of shutdown or restart, there must be something that causes Pebble to do compression or discard temporary data. Presumably, this is done and some point during normal execution but it is not clear when.

**Comment by masih** [comment]
Pebble runs compaction periodically and opportunistically e.g. on read as well as on flush which happens during shutdown I believe.

**Comment by gammazero** [comment]
Sufficient tests have been done to motivate moving to pebble. Closing issue.
